### ISSUE TITLE
faktura

### ISSUE THREAD

**Issue by jzelenka** [zauzoo/app#36]
@milant007 

Faktura jeste neni, ale na par veci se uz podivat muzes:
- das nova faktura, vyplnis billedTo a pak muzes pridavat polozky

Zbyva:
- zobrazeni souctu cele faktury
- save
- zobrazeni hlavicky vydane
- vydani
- tisk, zobrazeni pdf

**Comment by milant007** [comment]
Teď dorazil email s dalším HU must - Export těch jejich XMLek. Zkoušel jsem filtrovat datum od do a u toho to vyhazuje chybu, a u čísel faktur filtrovat od do nejde. ale to nevim zda pujde udělat? Kdyz ne, muzou si FA vybrat a nad vybranymi udelat export do XML.

Text emailu:

There is one more thing in my mind, maybe I have forgotten to mention it and I am not sure if it is in the documentation or not. 
This xml  query should be built into the invoicing program, it has to be an own, separated menu point, an even the name should be:  ADÓHATÓSÁGI ELLENŐRZÉSI ADATSZOLGÁLTATÁS 
As I mentioned two kind of running (selection should be available from-to dates, and from to invoice numbers)

Sorry to ask it, but I am not sure:  is it a  Volvo owned newly built program, our it is an existing outsider program we buy?  
Because it is now a must for all Hungarian invoicing programs. What I mean is, that  maybe if you are in contract with an external  program supplier (and if they have a Hungarian dealer or contact ) maybe it would be better to ask them to contact the Hungarian partner as well .
Of course I do my best, bit it is not the same  Of course if it is an own program, than we have no other way to solve this right now..

**Comment by jzelenka** [comment]
no, uplne jsem nepochopil co je treba udelat, zavolam.

**Comment by jzelenka** [comment]
jeste tisky a dokumenty, jinak hotove.

**Comment by jzelenka** [comment]
tiskou jsou, zaviram
